# Conjunto de servidores que funcionan para hacer monitoreo de equipos
# Le doy un nombre descriptivo al stack para saber de que se trata
name: monitoreo

services:
  # Base de datos para utilizar con grafana, sirve para recolectar datos de varias fuentes
  # https://prometheus.io/docs/prometheus/latest/installation/
  # https://docker-ip:9090/
  prometheus:
    # Confiuracion del dock
    container_name: prometheus
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # Configuracion de puertos, no se declara puertos ya que no hace falta por la configuracion de la red y NPM
    # ports:
     # - '9090:9090'
    restart: always
    # Configuracion de discos
    # Es muy importante que los directorios existan para que el stack funcione
    volumes:
      - prometheus-config:/etc/prometheus
      - prometheus:/prometheus
    depends_on:
      - node-exporter
      - blackbox-exporter
      - cadvisor
    # Le doy un nombre al stack para referirlo con NPM y le damos la red correspondiente
    hostname: prometheus
    networks:
      lan-docker:
        # ipv4_address: 192.168.200.254
  # FIN prometheus

  # Stack para habilitar el monitoreo en un servidor grafana ya funcionando
  # Al igual que otros stacks esta con la configurcion de IP definida
  # Con esto vamos a obtener informacion de la maquina
  # https://github.com/prometheus/node_exporter
  # https://prometheus.io/docs/guides/node-exporter/
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    # Para que se pueda conectar tenemos que exponer el puerto
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    # Le doy un nombre al stack para referirlo con NPM y le damos la red correspondiente
    hostname: node-exporter
    networks:
      lan-docker:
  # FIN node-exporter

    # Este contenedor es el que va a monitoreear los certificados ssl de docker
  # https://github.com/ribbybibby/ssl_exporter
  # https://grafana.com/grafana/dashboards/11279-ssl-cerificates/
  ssl-docker:
    container_name: ssl-cert
    image: ribbybibby/ssl-exporter
    restart: unless-stopped
    # Para que se pueda conectar tenemos que exponer el puerto
    ports:
      - '9219:9219'
    # Le doy un nombre al stack para referirlo con NPM y le damos la red correspondiente
    hostname: ssl-docker
    networks:
      lan-docker:
  # FIN ssl-docker

  # Con esto vamos a obtener informacion de la pagina web
  # https://github.com/prometheus/blackbox_exporter
  # https://github.com/prometheus-community/prometheus-playground/blob/master/blackbox-exporter/docker-compose.yml
  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    # Para que se pueda conectar tenemos que exponer el puerto
    ports:
      - '9115:9115'
    # Le doy un nombre al stack para referirlo con NPM y le damos la red correspondiente
    hostname: blackbox-exporter
    networks:
      lan-docker:
  # FIN blackbox-exporter

  # Este contenedor es el que va a monitoreear docker
  # https://prometheus.io/docs/guides/cadvisor/#docker-compose-configuration
  # https://grafana.com/grafana/dashboards/893-main/
  # https://github.com/google/cadvisor
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor #google/cadvisor:latest
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    # Para que se pueda conectar tenemos que exponer el puerto
    ports:
      - '8080:8080'
    # Le doy un nombre al stack para referirlo con NPM y le damos la red correspondiente
    hostname: cadvisor
    networks:
      lan-docker:
  # FIN cadvisor

  # Motor para crear graficos y dashboards desde distintos servicios, proetheus, loki, zabbix, etc
  # https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
  # https://docker-ip:3000/
  # Usuario y pass: admin
  grafana:
    # Confiuracion del dock
    container_name: grafana
    image: grafana/grafana-oss
    # Configuracion de puertos, no se declara puertos ya que no hace falta por la configuracion de la red y NPM
    # ports:
      # - "3000:3000"
    restart: always
    # Hago varias configuraciones interesantes
    environment:
      # Le doy una url para que sea mas facil ingresar
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
      # Plugins para cargar
      - GF_INSTALL_PLUGINS=${GRAFANA_PLUGINS}
      # Se puede definir un usuario y contraseña para no utilizar el que viene por defecto
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    # Configuracion de discos
    # Es muy importante que los directorios existan para que el stack funcione
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
    # Le doy un nombre al stack para referirlo con NPM y le damos la red correspondiente
    hostname: grafana
    networks:
      lan-docker:
  # FIN grafana

  # Este es un explorador de archivos donde podemos ver, subir, etc archivos desde el servidor. Muy util para evitar utilizar ssh o ftp
  # https://filebrowser.org/installation
  # Usuario y Password: admin
#  file-browser:
    # Le doy un nombre al dock
#    container_name: file-browser
#    image: filebrowser/filebrowser
    # Configuracion de puertos, no lo declara puertos ya que uso la configuracion de la red y NPM
    # ports:
      # - "8080:80"
#    restart: always
    # Le activo la terminal
#    tty: true
    # Como hago uso de los volumenes para persistencia de datos aca se declaran los directorios, es muy importante que los directorios existan para que el stack funcione. Utilizo la variable ${PATH_DATA} definida en el archivo.env para referirme al directorio.
#    volumes:
#      - ${DOCKER_PATH}:/srv
    # Le doy un nombre al host para referirlo con NPM
#    hostname: file-browser
#    networks:
#      lan-docker:
  # FIN file-browser

# Declaramos la red que vamos a utilizar
networks:
  # Configuracion de la red lan-docker
  lan-docker:
    external: true

# Como hago uso de los volumenes aca hago las declaraciones
# Es muy importante que los directorios existan para que el stack funcione
volumes:
  # Volumen ara guardar la configuracion
  prometheus-config:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      # device: /mnt/docker-data/prometheus/config
      device: ${DOCKER_PATH}/prometheus/config
      o: bind
    name: prometheus-config
  # Volumen ara guardar los datos de prometheus
  prometheus:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      # device: /mnt/docker-data/prometheus/data
      device: ${DOCKER_PATH}/prometheus/data
      o: bind
    name: prometheus
  # Volumen ara guardar los datos de grafana
  grafana:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ${DOCKER_PATH}/grafana
      o: bind
    name: grafana
