# Le doy un nombre descriptivo al stack para saber de que se trata
name: exporters-prometheus

services:
  # Contenedor para obtener informacion de la maquina
  # https://github.com/prometheus/node_exporter
  # https://prometheus.io/docs/guides/node-exporter/
  node-exporter:
    # Le doy un nombre al dock
    container_name: node-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    # Para que se pueda conectar tenemos que exponer el puerto
    ports:
      - '9100:9100'
    # No tiene directorios especiales ya que guarda los datos en la BD de prometheus
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    # Le doy un nombre al host para referirlo en la configuracion de prometheus
    hostname: node-exporter
    networks:
      lan_docker:
        # Si queremos darle una IP estatica cambiamos la siguiente linea
        # ipv4_address: 192.168.200.254
  # FIN node-exporter

  # Este contenedor es el que va a monitoreear los certificados ssl de docker
  # https://github.com/ribbybibby/ssl_exporter
  # https://grafana.com/grafana/dashboards/11279-ssl-cerificates/
  ssl-docker:
    container_name: ssl-docker
    image: ribbybibby/ssl-exporter
    restart: unless-stopped
    # Para que se pueda conectar tenemos que exponer el puerto
    ports:
      - '9219:9219'
    # Le doy un nombre al stack para referirlo con NPM y le damos la red correspondiente
    hostname: ssl-docker
    networks:
      lan_docker:
  # FIN ssl-cert

  # Con este contenedor vamos a obtener informacion de cualquier pagina web
  # https://github.com/prometheus/blackbox_exporter
  # https://github.com/prometheus-community/prometheus-playground/blob/master/blackbox-exporter/docker-compose.yml
  blackbox-exporter:
    # Le doy un nombre al dock
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    # Para que se pueda conectar tenemos que exponer el puerto
    ports:
      - '9115:9115'
    # Le doy un nombre al host para referirlo en la configuracion de prometheus
    hostname: blackbox-exporter
    networks:
      lan_docker:
      # Si queremos darle una IP estatica cambiamos la siguiente linea
      # ipv4_address: 192.168.200.254
  # FIN blackbox-exporter

  # Este contenedor monitorizamos docker
  # https://prometheus.io/docs/guides/cadvisor/#docker-compose-configuration
  # https://grafana.com/grafana/dashboards/893-main/
  # https://github.com/google/cadvisor
  cadvisor:
    # Le doy un nombre al dock
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor #google/cadvisor:latest
    restart: unless-stopped
    # Para que se pueda conectar tenemos que exponer el puerto
    ports:
      - '8080:8080'
    # No tiene directorios especiales ya que guarda los datos en la BD de prometheus
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    # Le doy un nombre al host para referirlo en la configuracion de prometheus 
    hostname: cadvisor
    networks:
      lan_docker:
      # Si queremos darle una IP estatica cambiamos la siguiente linea
      # ipv4_address: 192.168.200.254
  # FIN cadvisor

# Declaramos la red que vamos a utilizar
networks:
  # Configuracion de la red lan_docker, si ya hay una red configurada dejamos esta linea y cambiamos el nombre por el correcto
  lan_docker:
    external: true
    # Para utilizar solo este repositorio hay que configurar bien la red, comentar la linea de arriba y dejal activas las siguientes:
    # driver: bridge
    # ipam:
      # config:
        # - subnet: 192.168.200.0/24
          # gateway: 192.168.200.1
