{
 "title": "Monitoreo Paginas Web",
 "tags": [
  "Desarrollo",
  "Web"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_success{geohash!~\"PrivDock|PubDock\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Vision General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vision General",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\", geohash=\"URL\"}"
    },
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\", geohash=\"Publica\"}"
    },
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\", geohash=\"Privada\"}"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\"} - time()"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  { "title": "Estado de $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "instance" },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\", geohash=\"URL\"}"
    },
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\", geohash=\"Publica\"}"
    },
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\", geohash=\"Privada\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso discos",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Detalle de discos",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$instance',fstype!~\"(tmpfs|vfat|ramfs)\"}-node_filesystem_free_bytes{instance=~'$instance',fstype!~\"(tmpfs|vfat|ramfs)\"}) *100/(node_filesystem_avail_bytes {instance=~'$instance',fstype!~\"(tmpfs|vfat|ramfs)\"}+(node_filesystem_size_bytes{instance=~'$instance',fstype!~\"(tmpfs|vfat|ramfs)\"}-node_filesystem_free_bytes{instance=~'$instance',fstype!~\"(tmpfs|vfat|ramfs)\"}))",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$instance\",fstype!~\"(tmpfs|vfat|ramfs)\"}",
     "legendFormat": "Libre"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance\",fstype!~\"(tmpfs|vfat|ramfs)\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duracion DNS Lookup",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Duracion HTTP Probe",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}[1m])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Uso de RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"} > 0",
     "legendFormat": "Libre"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} > 0",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"} > 0",
     "legendFormat": "Disponible"
    }
   ]
  },
  {
   "title": "Trafico de RED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\",device=~\"(?i)^(ens|eth).+$\"}[$__rate_interval])",
     "legendFormat": "IN ({{device}})"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance\",device=~\"(?i)^(ens|eth).+$\"}[$__rate_interval])",
     "legendFormat": "OUT ({{device}})"
    }
   ]
  }
 ]
}