{
 "title": "Monitoreo Docker",
 "tags": [
  "Desarrollo",
  "Web",
  "Docker"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(cadvisor_version_info{job=\"Webs\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cadvisor_version_info{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "proyecto",
    "label": "Proyecto",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$instance\"},container_label_com_docker_compose_project)"
    }
   },
   {
    "name": "contenedor",
    "label": "Contenedor",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\", instance=~\"$instance\", container_label_com_docker_compose_project=~\"$proyecto\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Vista General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estado Paginas WEB",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "ssl_prober{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ssl_probe_success{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ssl_cert_not_after{instance=~\"$instance\", issuer_cn!~\"ISRG Root X1\"} - time()",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ssl_tls_version_info{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contenedores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$instance\", name=~\".+\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\", geohash=\"PubDock\"}"
    },
    {
     "expr": "probe_success{instance=~\"$instance\", geohash=\"PrivDock\"}"
    }
   ]
  },
  {
   "title": "Uso de RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}) / node_memory_MemTotal_bytes{instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}[1m])) by (instance))*100",
     "legendFormat": "Uso de CPU"
    }
   ]
  },
  {
   "title": "Uso discos",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}[1m])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Contenedores",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"$instance\", name=~\"$contenedor\"}[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_spec_memory_limit_bytes{instance=\"$instance\", name=~\"$contenedor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"$instance\", name=~\"$contenedor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - container_start_time_seconds{instance=~\"$instance\", name=~\"$contenedor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uso de RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"} > 0",
     "legendFormat": "Libre"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} > 0",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"} > 0",
     "legendFormat": "Disponible"
    }
   ]
  },
  {
   "title": "Trafico de red",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\", device=~\"eth.*|ens.*\"}[$__rate_interval])",
     "legendFormat": "IN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$instance\", device=~\"eth.*|ens.*\"}[$__rate_interval])",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Detalle de discos",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$instance',fstype!~\"(tmpfs|vfat|ramfs)\"}-node_filesystem_free_bytes{instance=~'$instance',fstype!~\"(tmpfs|vfat|ramfs)\"}) *100/(node_filesystem_avail_bytes {instance=~'$instance',fstype!~\"(tmpfs|vfat|ramfs)\"}+(node_filesystem_size_bytes{instance=~'$instance',fstype!~\"(tmpfs|vfat|ramfs)\"}-node_filesystem_free_bytes{instance=~'$instance',fstype!~\"(tmpfs|vfat|ramfs)\"}))",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$instance\",fstype!~\"(tmpfs|vfat|ramfs)\"}",
     "legendFormat": "Libre"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance\",fstype!~\"(tmpfs|vfat|ramfs)\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Detalles por contenedor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"$instance\", name=~\"'.+'|$contenedor\", container_label_com_docker_compose_project=~\"$proyecto\"}[$__rate_interval]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uso de RAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$instance\", job=~\"$job\", name=~\"$contenedor\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Trafico de red",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$instance\", job=~\"$job\", name=~\"$contenedor\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}} OUT"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$instance\", job=~\"$job\", name=~\"$contenedor\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}} IN"
    }
   ]
  },
  {
   "title": "Uso de disco",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=~\"$instance\", name=~\"$contenedor\"}/container_fs_limit_bytes{instance=~\"$instance\", name=~\"$contenedor\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_fs_usage_bytes{instance=~\"$instance\", name=~\"$contenedor\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_fs_limit_bytes{instance=~\"$instance\", name=~\"$contenedor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}